### ISSUE TITLE
Wrong/multiple emails being displayed

### ISSUE THREAD

**Issue by ianlayton** [MidwestFurryFandom/mff-rams-plugin#39] opened 2018-05-24 01:42 UTC
When viewing a registration history, multiple emails (including ones not associated with the registration)

http://rams.test.furfest.org/rams/registration/history?id=9056b402-f3b0-43cb-a9a2-7788ddeead58

Note: This may be because the registrations were created in the same session (but not the same payment). I tested another registration where I closed all the browsers to Rams, reopened and registered another person. 

http://rams.test.furfest.org/rams/registration/history?id=0d8d96a3-c732-4f1d-b918-f3eb59cc1139

This one appears to have worked correctly.

**Comment by kitsuta** [comment] 2018-05-24 02:57
This is actually working as designed.

The common factor here isn't the session -- it's the email address you used.
![image](https://user-images.githubusercontent.com/7198215/40462101-7d6abe3e-5edc-11e8-838b-a654e7948b75.png)
(the first two attendees haven't received emails because they're comped, which seems to match what you described in https://github.com/MidwestFurryFandom/mff-rams-plugin/issues/40)

The query for this page is:
```
session.query(Email)
  .filter(or_(Email.to == attendee.email,
                  and_(Email.model == 'Attendee', Email.fk_id == id)))
            .order_by(Email.when).all(),
```

So it's specifically selecting _either_ a matching email address _or_ an email sent to an Attendee with the same id.

**Comment by jmdawson** [comment] 2018-07-12 15:12
It's mostly showing us an issue that crops up in testing, because we only have a handful of emails to test with.  Since we understand the issue and it's not a big deal in prod, I'm closing this for now. Perhaps MAG will have thoughts on this in the future, or perhaps we will, but not this year.

**Closed by jmdawson** 2018-07-12 15:12 UTC
Labels: enhancement, registration
